### ISSUE TITLE
A bit lost with kandy vs letsplot

### ISSUE THREAD

**Issue by CGenie** [Kotlin/kandy#397]
Hello,
I'm just exploring Kotlin notebooks.

I have a simple cell with this code:
```kotlin
val rand = java.util.Random(37)
val data = mapOf (
    "rating" to List(200) { rand.nextGaussian() } + List(200) { rand.nextGaussian() * 1.5 + 1 },
    "cond" to List(200) { "A" } + List(200) { "B" }
)

letsPlot(data) { x = "rating"; fill = "cond" } + ggsize(700, 300) +
        geomDensity(color = "dark_green", alpha = .7) + scaleFillBrewer(type = "seq") +
        theme(panelGridMajorX = "blank")
```
However, it doesn't render in Kotlin notebook.

From what I see, `letsPlot` returns `org.jetbrains.letsPlot.intern.Plot`.

And compared with this (which does render the graphics properly):
```kotlin
plot(data) {
    x("cond"<String>())

    bars {
        // name = "test"
        y("rating"<Double>())
        fillColor("rating") {
            scale = continuous(range=Color.YELLOW..Color.RED)
        }
    }
}
```
I see it returns `org. jetbrains. kotlinx. kandy. ir.Plot`.

Is there a way to convert a `letsPlot` output to a Kandy one to render the graphics properly?

**Comment by CGenie** [comment]
Ah, ok, maybe this one is related: https://github.com/JetBrains/lets-plot-kotlin/issues/244

**Comment by AndreiKingsley** [comment]
Hi! To enable the rendering of lets-plot charts, you need to add the line
```
%use lets-plot
```
to your notebook.

**Comment by CGenie** [comment]
But I did, here's what my snippet looks like and I don't see the rendered plot:
https://gitlab.com/-/snippets/3728123

Here's a similar notebook for Kandy where the plot is rendered correctly:
https://gitlab.com/-/snippets/3728124

**Comment by AndreiKingsley** [comment]
I have 404 on your links.
What is your version of Notebook?

**Comment by CGenie** [comment]
I changed visibility of the snippets, should be working now.

I'm on intellij idea 2024.1.4 with kotlin notebook version 241.17011.79

**Comment by AndreiKingsley** [comment]
And also please specify the kernel version (can be found in Kotlin Notebook plugin settings)

**Comment by CGenie** [comment]
Kernel version is 0.12.0-226

**Comment by CGenie** [comment]
BTW, I had to set `-jvm-target=11` and `JVM target for snippets` to 11 because otherwise kandy complained (in `plot`) that jvm 1.8 runtime conflicts with 11.

**Comment by AndreiKingsley** [comment]
Yes Kandy has jvm 11 target, so it's incompatible with 1.8.
Unfortunately I couldn't reproduce the bug yet, but I'll keep looking into it.
And yeah, you asked above, Lets-Plot plots can't be converted to Kandy plots, but Kandy plots can be converted to Lets-Plot ones (via `.toLetsPlot()` extension).

Lets-Plot charts use web outputs (while Kandy uses native rendering via Swing) - maybe that's the issue, try testing them with the simplest option (e.g. `HTML("Simple html text")` line). The notebook must have "Trusted" flag enabled to them display them.

**Comment by zakurdaevm** [comment]
@CGenie 
hi!
About:
> Apparently even HTML("...") doesn't render as well.

Could you please specify the next information about versions, and I will try to reproduce it:
* your IDEA version
* plugins versions 
   * org.jetbrains.plugins.kotlin.jupyter, 
   * intellij.jupyter

You can get this info by double shift -> type 'About' -> Copy and close
I just check it with Build #IU-241.18034.62, built on June 20, 2024 and it works fine for me

![Monosnap default-empty – nte2 ipynb 2024-07-12 14-42-33](https://github.com/user-attachments/assets/d43e332b-5bda-4703-bd88-66c862d3c68f)

**Comment by zakurdaevm** [comment]
@CGenie 
> I'm on intellij idea 2024.1.4 with kotlin notebook version 241.17011.79

Sorry, I missed that you had mentioned it earlier. 
Let me try to reproduce it.

**Comment by zakurdaevm** [comment]
@CGenie 
Can I ask you to update the plugins to version Version: 2024.1.4 Build: 241.18034.62? 
In this version, everything should work fine. (and plot renders and weboutputs work fine)

<img width="942" alt="Monosnap default-empty – nte2 ipynb 2024-07-12 15-28-25" src="https://github.com/user-attachments/assets/8abb4456-98e4-47b3-8312-9c95ed6597be">

**Comment by CGenie** [comment]
Sure, it's just I'm not quite sure how: the plugins intellij dialog doesn't show any info about new version and https://plugins.jetbrains.com/plugin/16340-kotlin-notebook/versions doesn't mention 241.18034.62 I think

**Comment by zakurdaevm** [comment]
@CGenie 
hi again!
thank you for the information about the plugin version!

I could reproduce the issue you mentioned above with your version.  

We just published [new plugin version](https://plugins.jetbrains.com/plugin/16340-kotlin-notebook/versions/stable/570821) for Kotlin Notebook 241.18034.95 with fixes

![Monosnap Versions: Kotlin Notebook Plugin for IntelliJ IDEA | JetBrains Marketplace 2024-07-12 23-05-04](https://github.com/user-attachments/assets/0cd02c73-c394-4bb6-845f-a13162152c49)

Could you please download and install it and restart IDE?
It should work fine now. 

<img width="300" alt="Monosnap default-empty – nte2 ipynb 2024-07-12 23-06-14" src="https://github.com/user-attachments/assets/50aefda3-1497-4bc6-8e13-b6ef1a79fbe7">

**Comment by CGenie** [comment]
Hm, I upgraded, restarted the IDE but it still doesn't render for me. I added some tracebacks, maybe some library that I have is outdated?

https://gitlab.com/-/snippets/3728475

Thank you for your very fast responses, this is top notch support :)

**Comment by zakurdaevm** [comment]
hm, that's a bit strange. 
As I can see from your snippet at least HTML (web outputs rendering) should already works.

1) Could you please run a code like this
`HTML("<h1>Header H1</h1>")`

and you should see something like this:
![Monosnap default-empty – nte2 ipynb 2024-07-13 11-23-55](https://github.com/user-attachments/assets/93429d6b-52d9-42c5-9a14-b6e5a50b6a9b)

2) Also could you please check plugins versions of Kotlin Notebook plugin and Jupyter:
![Monosnap Settings 2024-07-13 11-24-39](https://github.com/user-attachments/assets/b6a1cb73-8c02-49da-a317-33b54bb230c4)

**Comment by CGenie** [comment]
Ah, I didn't notice that but the gitlab notebook renders HTML properly, while in Idea I don't see it...

![Screenshot from 2024-07-15 05-49-00](https://github.com/user-attachments/assets/105e2efe-679c-4da2-a1fc-2e18afb57f4e)

**Comment by zakurdaevm** [comment]
Ok, got it. 
Could you please specify the plugins versions and operating system?
plugins:
- Jupyter
- Kotlin notebook

**Comment by CGenie** [comment]
OK so I downloaded Idea now, it's at version 241.18034.62 and from what I see it renders properly (I'm on Mandriva Linux).

Previously I used system packages (which has the same 241.18034.62 version) and it doesn't render the graphics properly...


https://aur.archlinux.org/packages/intellij-idea-ultimate-edition this is the package I'm using.

**Comment by zakurdaevm** [comment]
ok, thank you for update!
Does it mean that for now everything works and renders fine?

**Comment by CGenie** [comment]
Yes, thank you!
